"""empty message

Revision ID: 1453ece69042
Revises: 
Create Date: 2021-09-24 09:08:42.309099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1453ece69042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendation_present',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recomendation', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutoriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urlpresentaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('urlpresentaciones')
    op.drop_table('tutoriales')
    op.drop_table('recomendation_present')
    # ### end Alembic commands ###
