"""empty message

Revision ID: 5b6f9e78f1b7
Revises: 78abeb7143ed
Create Date: 2021-09-30 14:32:15.366304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6f9e78f1b7'
down_revision = '78abeb7143ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sugerencias_user_id_fkey', 'sugerencias', type_='foreignkey')
    op.drop_column('sugerencias', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sugerencias', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sugerencias_user_id_fkey', 'sugerencias', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
